/**
 * 바이브 카페 메뉴 데이터 및 Supabase SQL 쿼리 템플릿 정의 파일
 */

// 음료 메뉴 목록 및 기본 가격 정의
export interface DrinkMenuItem {
  id: string;
  name: string;
  price: number;
}

export const DRINK_MENU: DrinkMenuItem[] = [
  { id: 'americano', name: '아메리카노', price: 3500 },
  { id: 'latte', name: '카페라떼', price: 4000 },
  { id: 'mocha', name: '카페모카', price: 4500 },
  { id: 'vanilla', name: '바닐라라떼', price: 4500 },
  { id: 'greentea', name: '녹차라떼', price: 4500 },
];

// 음료 사이즈 목록 및 추가 가격 정의
export interface SizeOption {
  id: 'S' | 'M' | 'L';
  name: string;
  extraPrice: number;
}

export const SIZE_OPTIONS: SizeOption[] = [
  { id: 'S', name: 'S', extraPrice: 0 },
  { id: 'M', name: 'M', extraPrice: 500 },
  { id: 'L', name: 'L', extraPrice: 1000 },
];

// 추가 옵션 목록 및 가격 정의
export interface ExtraOption {
  id: string;
  name: string;
  price: number;
}

export const EXTRA_OPTIONS: ExtraOption[] = [
  { id: 'shot', name: '샷 추가', price: 500 },
  { id: 'cream', name: '크림 추가', price: 500 },
  { id: 'syrup', name: '시럽 추가', price: 300 },
  { id: 'decaf', name: '디카페인', price: 0 },
];

// 접수된 주문 인터페이스 정의
export interface CafeOrder {
  id: string;
  customerName: string;
  phone: string;
  drinkName: string;
  drinkPrice: number;
  size: 'S' | 'M' | 'L';
  sizePrice: number;
  options: string[];
  optionsPrice: number;
  quantity: number;
  requests: string;
  totalPrice: number;
  createdAt: string;
}

// Supabase SQL Editor용 테이블 생성 및 더미데이터 쿼리문
export const SUPABASE_SQL_CREATE_TABLE = `-- 1. cafe_menu 테이블 생성 쿼리 (주문서 항목 반영)
CREATE TABLE IF NOT EXISTS public.cafe_menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 주문 고유 번호
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL, -- 주문 일시
    customer_name VARCHAR(50) NOT NULL, -- 1. 주문자 이름 (필수)
    phone VARCHAR(20),                  -- 2. 전화번호
    drink VARCHAR(50) NOT NULL,         -- 3. 선택 음료
    drink_price INTEGER NOT NULL,       -- 음료 기본 가격
    size VARCHAR(10) NOT NULL DEFAULT 'M', -- 4. 사이즈 (S, M, L)
    size_price INTEGER NOT NULL DEFAULT 500, -- 사이즈 추가 금액
    options TEXT[] DEFAULT '{}',        -- 5. 추가 옵션 목록 (배열)
    options_price INTEGER NOT NULL DEFAULT 0, -- 옵션 추가 총액
    quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity >= 1 AND quantity <= 10), -- 6. 수량 (1~10)
    requests TEXT,                      -- 7. 요청사항
    total_price INTEGER NOT NULL,       -- 총 예상 결제 금액
    order_status VARCHAR(20) DEFAULT '접수완료' -- 주문 처리 상태
);

-- RLS (Row Level Security) 활성화 (선택 사항)
ALTER TABLE public.cafe_menu ENABLE ROW LEVEL SECURITY;

-- 익명 사용자(anon) 및 인증 사용자(authenticated) 모두 읽기/쓰기 허용 정책 (테스트 및 공개 주문용)
CREATE POLICY "누구나 주문 등록 가능" ON public.cafe_menu
    FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY "누구나 주문 내역 조회 가능" ON public.cafe_menu
    FOR SELECT TO anon, authenticated USING (true);
`;

export const SUPABASE_SQL_INSERT_DUMMY = `-- 2. 테스트용 1건 가짜 데이터 삽입 (INSERT) 쿼리
INSERT INTO public.cafe_menu (
    customer_name,
    phone,
    drink,
    drink_price,
    size,
    size_price,
    options,
    options_price,
    quantity,
    requests,
    total_price,
    order_status
) VALUES (
    '홍길동',
    '010-1234-5678',
    '카페라떼',
    4000,
    'M',
    500,
    ARRAY['샷 추가'],
    500,
    1,
    '얼음 적게 부탁드립니다.',
    5000,
    '접수완료'
);
`;
